### ISSUE TITLE
Broken frontend

### ISSUE THREAD

**Issue by macor161** [macor161/aragon-drive-app#69]
The standalone frontend (npm run start:frontend) seems broken since the upgrade to Babel 7. 
Storybook displays the following error:

```
ERROR in ./.storybook/config.js
Module build failed (from /home/mathew/workspace/datastore/aragon-drive/node_modules/babel-loader/lib/index.js):
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/home/mathew/workspace/datastore/aragon-drive/app/frontend/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/home/mathew/workspace/datastore/aragon-drive/app/frontend/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/home/mathew/workspace/datastore/aragon-drive/app/frontend/node_modules/@babel/plugin-proposal-decorators/lib/index.js:35:7)
    at /home/mathew/workspace/datastore/aragon-drive/app/frontend/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/home/mathew/workspace/datastore/aragon-drive/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/home/mathew/workspace/datastore/aragon-drive/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /home/mathew/workspace/datastore/aragon-drive/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/mathew/workspace/datastore/aragon-drive/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/mathew/workspace/datastore/aragon-drive/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/mathew/workspace/datastore/aragon-drive/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/mathew/workspace/datastore/aragon-drive/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/mathew/workspace/datastore/aragon-drive/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/mathew/workspace/datastore/aragon-drive/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/mathew/workspace/datastore/aragon-drive/node_modules/babel-loader/lib/index.js:50:20)
    at /home/mathew/workspace/datastore/aragon-drive/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/home/mathew/workspace/datastore/aragon-drive/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

**Comment by juslar** [comment]
Just fixed the problem and pushed on dev :) Just needed the babel-bridge package and to import babel/polyfill in the app.js file! Closing this issue.
